on:
  workflow_dispatch:
  
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v4
      with:
        node-version: 14
    - run: npm install
    - run: npm run build
